export const conferences = [
  {
    cid: 1,
    title: 'Cypherpunk 2023 ',
    brief:
      'CypherPunk 2023 will expand your education about blockchain projects, Web3, decentralization, AI and disruptive technology. Come listen to some of the most educated speakers in the field!',
    desc: '',
    cover: '/images/cypherpunk2023.jpg',
    start_time: '20230926 9:00AM',
    end_time: '20230926 12:00AM',
    venue: 'China, Shanghai, 东方大酒店',
    host: {
      id: 1,
      name: 'Cypherpunk DAO',
      logo: '/images/logos/bitcoin-btc-logo.png',
      website: 'www.cd.com',
      verified: true,
    },
    origin: 'https://www.web3event.org/event/2564#explore',
    side_events_count: 11874,
  },
  {
    cid: 2,
    title: 'A³ Summit - Accelerate Web3 Adoption in Asia ',
    brief:
      "The A³ Summit connects Web2 and Web3 experts, featuring discussions on Web3's future, merging forces from Asia and global VCs. Topics include Web2 to Web3 transition, innovation, and industry insights. Co-hosted by ZAN, Artela, Trusta Labs, SynFutures, Web3Port, HashKey Capital, and Alibaba Cloud. Traffic guidance is provided for attendees.",
    desc: 'bela bela',
    cover: '/images/a3summit.jpeg',
    start_time: '20230926 9:00AM',
    end_time: '20230926 12:00AM',
    venue: 'Singapore, Marina Sands',
    host: {
      id: 1,
      name: 'A3DAO',
      logo: '/images/logos/agentx-sky-logo.svg',
      website: 'www.a3dao.xyz',
      verified: false,
    },
    origin: 'https://www.web3event.org/event/5643#home',
    side_events_count: 5616,
  },
  {
    cid: 3,
    title: 'Newmetric Cradle发源地，摇篮/ˈkreɪdl/ Workshop at Cosmoverse 2023',
    brief:
      "In the world of blockchain, where smart contracts are immutable once deployed, the stakes for effective testing have never been higher. Yet, traditional testing methodologies fall short, offering a constrained and often cumbersome process that barely scratches the surface of what's possible.",
    desc: 'bela bela',
    cover: '/images/newmetric2023.jpeg',
    start_time: '20230926 9:00AM',
    end_time: '20230929 18:00PM',
    venue: 'USA, New York',
    host: {
      id: 1,
      name: 'Newmetric DAO',
      logo: '/images/logos/gitcoin-gtc-logo.svg',
      website: 'www.newmetric.xyz',
      verified: false,
    },
    origin: 'https://www.web3event.org/event/5643#home',
    side_events_count: 9232,
  },
  {
    cid: 4,
    title: '2023上海区块链国际周·第九届区块链全球峰会',
    brief:
      '“区块链新经济”系列区块链全球峰会是万向区块链实验室自2015年开始，于每年秋天在上海举办的以高质量内容为基础的区块链活动。2016年，万向区块链实验室在全球峰会的基础上，将活动扩展成为上海区块链国际周，为大家提供更丰富的了解全球区块链技术和应用进展的通道。',
    desc: 'bela bela',
    cover: '/images/shiw.jpg',
    start_time: '20230926 9:00AM',
    end_time: '20230929 18:00PM',
    venue: 'USA, New York',
    host: {
      id: 1,
      name: 'Hashkey Group',
      logo: '/images/logos/wechat-logo.png',
      website: 'www.hk.xyz',
      verified: true,
    },
    origin: 'https://www.huodongxing.com/event/3705109559000?qd=1139540375758',
    side_events_count: 1123,
  },
  {
    cid: 5,
    title: 'Streamlining Backlog Management',
    brief:
      'Immerse yourself in the world of efficient backlog management through our webinar on backlog management to accelerate the flow. Uncover the art of prioritizing tasks, optimizing workflows, and fostering collaboration. Join us to revolutionize your backlog approach and master the path to project success.',
    desc: 'bela bela',
    cover: '/images/st.webp',
    start_time: '20230926 9:00AM',
    end_time: '20230929 18:00PM',
    venue: 'Hong Kong',
    host: {
      id: 1,
      name: 'HKGHH',
      logo: '/images/logos/infura-bg.png',
      website: 'www.HKGHH.xyz',
      verified: true,
    },
    origin:
      'https://www.eventbrite.hk/e/let-deals-happen-happy-hour-drinks-for-pevcconsultancyfamily-offices-tickets-566286707787',
    side_events_count: 112,
  },
];
