export const conferencesList = [
  {
    cid: 1,
    title: 'ETH Hong Kong',
    brief: 'Connecting & Empowering Web3 Builders.',
    desc: '',
    cover: '/images/cover/ethhk-2023.png',
    start_time: '22 Oct 2023',
    end_time: '24 Oct 2023',
    venue: 'Cyberport, Hong Kong',
    host: [
      {
        id: 1,
        name: 'Scroll',
        logo: '/images/logos/bitcoin-btc-logo.png',
        website: 'www.cd.com',
        verified: true,
      },
      {
        id: 2,
        name: 'Newman Group',
        logo: '/images/logos/bitcoin-btc-logo.png',
        website: 'www.cd.com',
        verified: true,
      },
    ],
    origin: 'https://www.ethhongkong.co/',
    side_events_count: 100,
  },
  {
    cid: 2,
    title: 'Hong Kong FinTech Week',
    brief:
      'Main Conference will be held on 2-3 November at the Hong Kong Convention and Exhibition Centre. The Greater Bay Area Day will be held on 31 October.',
    desc: '',
    cover: '/images/cover/hk-fintech-week.png',
    start_time: '30 Oct 2023',
    end_time: '5 Nov 2023',
    venue: 'Convention & Exhibition Centre, Hong Kong',
    host: [
      {
        id: 1,
        name: 'FSTB',
        logo: '/images/logos/bitcoin-btc-logo.png',
        website: 'www.cd.com',
        verified: true,
      },
      {
        id: 2,
        name: 'InvestHK',
        logo: '/images/logos/bitcoin-btc-logo.png',
        website: 'www.cd.com',
        verified: true,
      },
    ],
    origin: 'https://www.fintechweek.hk/',
    side_events_count: 100,
  },
  {
    cid: 3,
    title: 'Devconnect 2023 @Istanbul',
    brief:
      "Devconnect aims to bring together Ethereum's most important builders, researchers, and its community.",
    desc: '',
    cover: '/images/cover/devconnect2023.jpg',
    start_time: '13 Nov 2023',
    end_time: '19 Nov 2023',
    venue: 'ISTANBUL, Türkiye',
    host: [
      {
        id: 1,
        name: 'Ethereum Foundation',
        logo: '/images/logos/bitcoin-btc-logo.png',
        website: 'https://devconnect.org/',
        verified: true,
      },
    ],
    origin: 'https://devconnect.org/',
    side_events_count: 100,
  },
];

export const peopleList = [
  {
    id: '1',
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    gender: 'male',
  },
  {
    id: '2',
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hair_color: 'n/a',
    skin_color: 'gold',
    eye_color: 'yellow',
    gender: 'n/a',
  },
  {
    id: '3',
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, blue',
    eye_color: 'red',
    gender: 'n/a',
  },
  {
    id: '4',
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hair_color: 'none',
    skin_color: 'white',
    eye_color: 'yellow',
    gender: 'male',
  },
  {
    id: '5',
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'brown',
    gender: 'female',
  },
  {
    id: '6',
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hair_color: 'brown, grey',
    skin_color: 'light',
    eye_color: 'blue',
    gender: 'male',
  },
  {
    id: '7',
    name: 'Beru Whitesun Lars',
    height: '165',
    mass: '75',
    hair_color: 'brown',
    skin_color: 'light',
    eye_color: 'blue',
    gender: 'female',
  },
  {
    id: '8',
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hair_color: 'n/a',
    skin_color: 'white, red',
    eye_color: 'red',
    gender: 'n/a',
  },
  {
    id: '9',
    name: 'Biggs Darklighter',
    height: '183',
    mass: '84',
    hair_color: 'black',
    skin_color: 'light',
    eye_color: 'brown',
    gender: 'male',
  },
  {
    id: '10',
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hair_color: 'auburn, white',
    skin_color: 'fair',
    eye_color: 'blue-gray',
    gender: 'male',
  },
];
